M48
; DRILL file {KiCad 8.0.5} date 2024-11-06T15:04:32-0600
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2024-11-06T15:04:32-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X47500Y-27000
X47700Y-46000
X67900Y-32800
X68000Y-44300
M30
